![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [25]:
my_array=np.arange(10)
print(my_array)

bakoiti=my_array[np.array(my_array%2!=0)]
print(bakoiti[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


In [26]:
my_array[::-2] #my_array[-1:-10:-2] o my_array[-1::-2] es hacer lo mismo

array([9, 7, 5, 3, 1])

In [10]:
print(np.flip(my_array[np.array(my_array%2!=0)])) #metodo FLIP (invierte la lista)

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [17]:
my_array=np.arange(10)
print(my_array)
ejer_2=np.array([x for x in my_array if x>=7 and x<=8]) #Compresion de listas
print(ejer_2[::-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


In [23]:
#OPCION 2
my_array=np.arange(10)
resultado = my_array[np.array((my_array == 8) | (my_array == 7))] #Tenemos dos condicioens
print(resultado[::-1])

[8 7]


In [27]:
my_array=np.arange(10)
print(my_array)
print(my_array[8:6:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [31]:
my_array=np.arange(10)
print(my_array)
ejer_3=np.array([x for x in my_array if x==2 or x==1 or x==0])[::-1]
print(ejer_3)

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]


In [28]:
my_array=np.arange(10)
print(my_array)
print(my_array[-8::-1]) #[2::-1]

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [30]:
matriz=np.arange(1,21).reshape(4,5) #4x5= 4 filas + 5 columnas
print(matriz)
print('-'*100)
#Invertimos filas y columnas
print(matriz[::-1,::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
----------------------------------------------------------------------------------------------------
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [31]:
print(np.flip(matriz)) #el metodo FLIP directamente invierte toda la matriz

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [11]:
matriz=np.arange(1,21).reshape(4,5)
print(matriz)
print('-'*100)
print(matriz[:2:,:2:]) #[fila,columna], inicio:fin:paso

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
----------------------------------------------------------------------------------------------------
[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [33]:
matriz=np.arange(1,21).reshape(4,5)
print(matriz)
print('-'*100)

print(matriz[:3:2,::2]) #Lo mismo que matriz[::2,::2]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
----------------------------------------------------------------------------------------------------
[[ 1  3  5]
 [11 13 15]]


In [34]:
matriz[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [15]:
matriz=np.arange(1,21).reshape(4,5)
print(matriz)
print('-'*100)

print(matriz[:3:,::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
----------------------------------------------------------------------------------------------------
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [19]:
x=np.array(['Loro','Perro','Gato','Loro','Perro'])
print(x)
print(x[np.array(x=='Loro')]) #x[x=='Loro'] es hacer lo mismo mas corto

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']
['Loro' 'Loro']


In [36]:
x=np.array(['Loro','Perro','Gato','Loro','Perro'])
print(x)
print(x[x=='Loro'])

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']
['Loro' 'Loro']


In [23]:
x=np.array(['Loro','Perro','Gato','Loro','Perro'])
print(x)
x_bool=np.array(x=='Loro') #Creo un booleano que devuelva True en caso de encontrar Loro
print(x_bool)

print(x[x_bool]) #Devuelve un array con los valores True

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']
[ True False False  True False]
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [26]:
secuencia=np.arange(20)
print(secuencia)

array=secuencia.reshape(2,5,2) #2 matrices de 5 filas y 2 columnas
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [28]:
matriz=np.arange(1,21).reshape(4,5) #4x5= 4 filas + 5 columnas
print(matriz)
print('-'*100)

print(matriz[::-1,::-1]) #Invertimos filas y columnas

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
----------------------------------------------------------------------------------------------------
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [35]:
#Opcion 1: bastante cutre pero funciona :)
my_array=np.arange(10)*0
my_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
my_array=np.zeros(10)
print(my_array)
#print(len(my_array))
print(my_array.nbytes) #El numero de bytes

my_array[3]=1 #Cuarto elemento el que esta en la tercera posicion
print(my_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [46]:
vector=np.arange(10,50,1)
#vector=np.arange(start=10,stop=50,step=1)
print(vector[::-1]) #star:stop:step

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [8]:
#Opcion 1
vector=np.array([1,2,0,0,4,0])
nuevo=np.array([j for j in range(len(vector)) if vector[j]!=0])
print(nuevo)

[0 1 4]


In [17]:
def ejer_13(vector):
    return (np.array([j for j in range(len(vector)) if vector[j]!=0]))

vector=np.array([1,2,0,0,4,0])
ejer_13(vector)

array([0, 1, 4])

In [41]:
def ejer_13(vector):
    return np.where(vector!=0)

vector=np.array([1,2,0,0,4,0])
ejer_13(vector)

(array([0, 1, 4], dtype=int64),)

In [12]:
#Opcion 2
vector=np.array([1,2,0,0,4,0])
indices=np.where(vector!=0)[0]
print(indices)

[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [14]:
np.random.seed(14) #Para que siempre que ejecutemos la celda nos genere los mismos valores poner esto
matriz=np.random.randint(100,size=(10,10)) #Aleatorios enteros del 0 al 100. Matriz 10x10
print(matriz)
print('Minimo: ',np.min(matriz))
print('Maximo:',np.max(matriz))

[[88 12 22 71 28 10 80 61 26 25]
 [87 32  4 77 10 10  0 86 84  5]
 [37 41 67 79 68 77 45 17  0 31]
 [ 9 59 27 90 43  1 71 63 10 45]
 [30 19 65 57 75 77 81 13 56 79]
 [41 21 13 67 61 74 57 78 92 60]
 [ 9 78  4 50 16 52  1 11  3 97]
 [12 28 85 17 83 48 35 32 81 10]
 [52 62 85 52 67 56 48 72 52 99]
 [86 86 56 12 50 59 76 55 33 80]]
Minimo:  0
Maximo: 99


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [42]:
np.random.seed(15)
mi_vector=np.random.randint(1000,size=(30))
print(mi_vector)
print('Media: ', sum(mi_vector)/len(mi_vector))

[456 757 908 645 887 384 156 667 199 715  85 630 943 221  17 749 927  23
 416 318 778 143 196 873  39 805  19 812 717 956]
Media:  514.7


In [43]:
mi_vector.mean() #Metodo para calcular la media!

514.7

In [44]:
print(np.mean(mi_vector)) #Con numpy

514.7


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [49]:
array_0=np.ones((4,4))
array_0[1:3,1:3]=0
print(array_0)


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [50]:
x=np.ones((8,8))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#La MEJOR FORMA
def funcion(tamaño):
    x=np.ones((tamaño,tamaño))
    x[1:-1,1:-1]=0
    return x

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [56]:
ejer_17=np.zeros((8,8))
ejer_17[::2,1::2]=1
ejer_17[1::2,::2]=1
print(ejer_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [66]:
matriz=np.array([[0,1],[1,0]]) #Creo una matriz 2x2
print(matriz)
print('-'*100)
print(np.tile(matriz,(4,4)))

[[0 1]
 [1 0]]
----------------------------------------------------------------------------------------------------
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [79]:
np.random.seed(19)
matriz=np.random.randint(1,20,size=(5,5))
print(matriz)
media=np.mean(matriz)
print('-'*100)
print('Media: ', media)
print('-'*100)
print('Normalizado:')
normalizado=(matriz-media)/np.std(matriz)
print(normalizado)
print('-'*100)

print('Media: ', normalizado.mean())
print('Desviacion: ', normalizado.std())

[[15  3  9 11  3]
 [ 3  6  2 11 19]
 [13  8 16  8 17]
 [ 8  8 10 12 10]
 [ 5  6  8 18 18]]
----------------------------------------------------------------------------------------------------
Media:  9.88
----------------------------------------------------------------------------------------------------
Normalizado:
[[ 1.0259388  -1.37860527 -0.17633323  0.22442411 -1.37860527]
 [-1.37860527 -0.77746925 -1.57898394  0.22442411  1.8274535 ]
 [ 0.62518146 -0.3767119   1.22631748 -0.3767119   1.42669615]
 [-0.3767119  -0.3767119   0.02404544  0.42480279  0.02404544]
 [-0.97784792 -0.77746925 -0.3767119   1.62707482  1.62707482]]
----------------------------------------------------------------------------------------------------
Media:  -1.7763568394002506e-16
Desviacion:  1.0


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8 (que los pase a negativo)

In [85]:
secuencia=np.arange(11) #Secuencia del 0 al 10
x=secuencia.copy() #Creamos una copia por seacaso
x[(x>3)& (x<8)]=-1
print(secuencia)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [88]:
secuencia=np.arange(11) #Secuencia del 0 al 10
x=secuencia.copy() #Creamos una copia por seacaso
x[(x>3)& (x<8)]*=-1
print(secuencia)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
