## NUMPY: CONCEPTOS CLAVE

In [2]:
import numpy as np 
from skimage.io import imread #Para leer imagenes
import matplotlib.pyplot as plt #Para trabajar con imagenes

### ARRAYS


#### Creacion de arrays

In [10]:
#Unidimensionales: vectores
print(np.array([1,2,3,4,5,6,7,8,9,10]))
print('-'*100)
print(np.arange(11)) #Empieza en el 0
print('-'*100)
print(np.arange(start=1,stop=11,step=1))
print('-'*100)
print(np.arange(1,11,1))
print('-'*100)
print(np.arange(1,11,1,np.float64))

[ 1  2  3  4  5  6  7  8  9 10]
----------------------------------------------------------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10]
----------------------------------------------------------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10]
----------------------------------------------------------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10]
----------------------------------------------------------------------------------------------------
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [43]:
#Multidimensionales: matrices
print([[1,2,3],[4,5,6],[7,8,9]]) #Una lista de listas (sin usar np)
print('-'*100)
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))
print('-'*100)
print(np.identity(3))
print('-'*100)
print(np.zeros((3,2),np.int32)) #np.int32 es opcional, si queremos especificar el tipo de dato
print('-'*100)
print(np.ones((3,4)))
print('-'*100)
print(np.full((3,4),22))
print('-'*100)
print(np.arange(20).reshape(5,4)) #Elementos del 0 al 20. Los coloca en una matriz 5x4

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------------------------------------------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------------------------------------------------------------------------------------------------
[[0 0]
 [0 0]
 [0 0]]
----------------------------------------------------------------------------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----------------------------------------------------------------------------------------------------
[[22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]]
----------------------------------------------------------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


#### Creacion de arrays aleatorios: RANDOM

In [30]:
print(np.random.rand(5)) #Crea un array de 5 elementos con los numeros aleatorios entre 0 y 1
# np.random.rand(10)*(b-a)+a con numeros aleatorios entre a y b
print('-'*100)
print(np.random.rand(3,4))

[0.27712116 0.72478161 0.66485022 0.19625179 0.71251264]
----------------------------------------------------------------------------------------------------
[[0.29621982 0.57642281 0.00930396 0.61870698]
 [0.34222755 0.90796978 0.4295271  0.24612824]
 [0.22117512 0.60178088 0.36048172 0.00757937]]


In [37]:
#Numeros aleatorios enteros con randint
print(np.random.randint(5,size=(5))) #aleatorios del 0 al 5
print('-'*100)
print(np.random.randint(2,8,size=(5))) #Aleatorios entre 2 y 8
print('-'*100)
print(np.random.randint(1,10,size=(3,4)))

[4 1 4 0 0]
----------------------------------------------------------------------------------------------------
[3 6 3 7 5]
----------------------------------------------------------------------------------------------------
[[9 3 9 6]
 [6 3 4 4]
 [1 2 2 1]]


In [35]:
dimen_3=np.random.randint(1,10,size=(4,5,3)) #4 matrices de 5x3
dimen_3

array([[[4, 4, 6],
        [8, 6, 6],
        [9, 5, 1],
        [6, 4, 1],
        [7, 8, 3]],

       [[1, 8, 7],
        [3, 3, 6],
        [1, 5, 9],
        [6, 1, 3],
        [5, 6, 1]],

       [[3, 3, 3],
        [2, 2, 2],
        [2, 5, 5],
        [9, 9, 7],
        [5, 6, 4]],

       [[8, 1, 2],
        [3, 9, 9],
        [7, 3, 1],
        [2, 7, 7],
        [1, 7, 8]]])

**Seed**

In [42]:
#Si queremos guardar los numeros aleatorios ejecutados plantamos una semilla
np.random.seed(123)
print(np.random.rand(5)) #El resultado obtenido se guarda en la semilla seed(123)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


In [41]:
np.random.seed(123) #Si queremos obtener el resultado anterior poner esto ANTES
np.random.rand(5)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])

#### Atributos del array

In [3]:
ejemplo=np.arange(1,10).reshape(3,3)
print(ejemplo)
print('-'*100)
print(ejemplo.ndim) #Numero de 'niveles'. 3x3 dos dimensiones. (se multiplican DOS cosas)
print('-'*100)
print(ejemplo.shape) #Tamaño de cada dimension
print('-'*100)
print(ejemplo.size) #Cantidad de elementos en todo el array
print('-'*100)
print(ejemplo.dtype)
print('-'*100)
print(ejemplo.itemsize) #Tamaño de bytes de cada item del array
print('-'*100)
print(ejemplo.nbytes) #Tamaño de bytes de todo el array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------------------------------------------------------------------
2
----------------------------------------------------------------------------------------------------
(3, 3)
----------------------------------------------------------------------------------------------------
9
----------------------------------------------------------------------------------------------------
int32
----------------------------------------------------------------------------------------------------
4
----------------------------------------------------------------------------------------------------
36


In [50]:
array_multi_3 = np.array([[[1,10], [2, 20], [3, 30]],
                          [[4, 40], [5, 50], [6, 60]],
                          [[7, 70], [8, 80], [9, 90]]])
print(array_multi_3)

print("ndim:", array_multi_3.ndim)
print("shape:", array_multi_3.shape)
print("size:", array_multi_3.size)

[[[ 1 10]
  [ 2 20]
  [ 3 30]]

 [[ 4 40]
  [ 5 50]
  [ 6 60]]

 [[ 7 70]
  [ 8 80]
  [ 9 90]]]
ndim: 3
shape: (3, 3, 2)
size: 18


#### Subarrays

x[ start : stop : step]

Por defecto (si no ponemos algun elemento): start= 0, stop= tamaño de la dimension, step= 1

In [5]:
# Array de 10 elementos
x = np.arange(10)
print(x)

print("Del primer elemento al quinto", x[0:5])

print("Del primero al quinto con saltos de dos", x[0:5:2])

print("Desde el quinto", x[5::]) #los mismo que: x[5:]

print("Desde el quinto hasta el penultimo", x[5:-1]) #CUIDADO VA AL N-1

print("Desde el quinto, al primero", x[5::-1])

print("Sacar una copia", x[:]) #x.copy()

print("Ultimos dos elementos",x[-2:])

[0 1 2 3 4 5 6 7 8 9]
Del primer elemento al quinto [0 1 2 3 4]
Del primero al quinto con saltos de dos [0 2 4]
Desde el quinto [5 6 7 8 9]
Desde el quinto hasta el penultimo [5 6 7 8]
Desde el quinto, al primero [5 4 3 2 1 0]
Sacar una copia [0 1 2 3 4 5 6 7 8 9]
Ultimos dos elementos [8 9]


In [13]:
#Array de multiples dimensiones
y=np.arange(1,16).reshape(3,5) #3 filas x 5 columnas
print(y)
print('-'*100)

#2 primeras filas y 3 primeras columnas. y[filas,columnas]
print(y[:2,:3])
print('-'*100)

#Todas las filas cada dos columnas
print(y[::,::2])
print('-'*100)

#Invertir filas
print(y[::-1,::])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [6 7 8]]
----------------------------------------------------------------------------------------------------
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]
----------------------------------------------------------------------------------------------------
[[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [18]:
#SUBARRAYS CON BOOLEANOS
notas=np.array([2,4,5,2,3,7,9])
aprobados=notas[np.array(notas>=5)]
print(aprobados)
print('-'*100)

print(np.array(notas>=5))

[5 7 9]
----------------------------------------------------------------------------------------------------
[False False  True False False  True  True]


In [33]:
#WHERE
xy = np.array([[1,2,3],
              [4,5,6]])


print(np.where(xy < 4, 10, 20)) #si se cumple la condicion va a la primera sino a la segunda

[[10 10 10]
 [20 20 20]]


Interseccion entre dos arrays: np.intersect1

In [ ]:
#np.intersect1d(array1, array2, assume_unique=False, return_indices=False)
#Metodo de numpy para calcular la interseccion entre dos arrays
#asume_unique: if true  the input arrays are both assumed to be unique
#return_indices: If True, the indices which correspond to the intersection of the two arrays are returned

#### Concatenado

In [20]:
print([1,2,3]+[1,2,3]) #Se concatenan horizontalmente ya que se suman dos ELEMENTOS
print('-'*100)
print(np.array([1,2,3])+np.array([1,2,3])) #SUMA DE VECTORES (no es un concatenado)

[1, 2, 3, 1, 2, 3]
----------------------------------------------------------------------------------------------------
[2 4 6]


In [26]:
x=np.array([1,1,1])
y=np.array([4,4,4])

print(np.concatenate((x,y))) #Si no especificamos en vectores se hace orizontalmente 
print('-'*100)

print(np.vstack([x,y])) #Concatenado vertical
print('-'*100)

print(np.hstack([x,y])) #Concatenado horizontal


[1 1 1 4 4 4]
----------------------------------------------------------------------------------------------------
[[1 1 1]
 [4 4 4]]
----------------------------------------------------------------------------------------------------
[1 1 1 4 4 4]


In [32]:
ejemplo=np.array([[1,2,3],[4,5,6]])
print(ejemplo)
print('-'*100)

print(np.concatenate([ejemplo,ejemplo]))
#Si no especificamos nada se toma axis=0 por defecto, concatenado vertical
print('-'*100)

print(np.concatenate([ejemplo,ejemplo],axis=1))
print('-'*100)

print(np.vstack([ejemplo,ejemplo]))
print('-'*100)

print(np.hstack([ejemplo,ejemplo]))



[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


#### Separado

In [7]:
x=np.arange(10)
print(x)
print('-'*100)

x1,x2=np.split(x,2) #Separa el array x por la mitad. Guardando la primera mitad en x1 y la segunda en x2
print(x1)
print(x2)



[0 1 2 3 4 5 6 7 8 9]
----------------------------------------------------------------------------------------------------
[0 1 2 3 4]
[5 6 7 8 9]
